<<<<<<< Updated upstream
import "./globals.css";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
=======
import type { Metadata } from "next"

import "./globals.css"
>>>>>>> Stashed changes

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
<<<<<<< Updated upstream
};
=======
}
>>>>>>> Stashed changes

export default function RootLayout({
	children,
}: {
<<<<<<< Updated upstream
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				{children}
				<Analytics />
				<SpeedInsights />
			</body>
		</html>
	);
=======
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>{children}</body>
		</html>
	)
>>>>>>> Stashed changes
}
